import test from 'node:test';
import assert from 'node:assert/strict';
import {visibleSize,gameLayout} from '../dist/layout.mjs';
import {FingerboardGame,DualThumbInput,demoPop,assistDemo,obstaclesBetween,needsLandscape,PHYSICS} from '../dist/engine.mjs';
function step(g,s){for(let t=0;t<s;t+=1/120)g.update(1/120);}
function fresh(){const g=new FingerboardGame();g.start();g.drainEvents();return g;}
test('browser chrome reduces usable height without magnification changing world size',()=>{assert.deepEqual(visibleSize(844,390,{width:844,height:300,scale:1}),{width:844,height:300});assert.deepEqual(visibleSize(844,390,{width:422,height:195,scale:2}),{width:844,height:390});});
test('phone layouts reserve touch controls and visible course space',()=>{for(const [w,h] of [[667,280],[844,320],[844,390],[932,430],[1200,760]]){const l=gameLayout(w,h,21);assert.ok(l.ground+l.controls+l.bottom<h);assert.ok(l.scale>0);assert.ok(l.ground-l.scale*290>=l.header);}});
test('safe top and bottom remain outside the board and controls at each phone size',()=>{for(const [w,h] of [[667,280],[844,390],[932,430]]){const l=gameLayout(w,h,21,20);assert.ok(l.header>=72);assert.ok(l.bottom>=21);assert.ok(l.ground-l.scale*290>=l.header);assert.ok(l.ground+l.controls+l.bottom<h);}});
test('portrait and square tablet viewports are gated consistently',()=>{assert.equal(needsLandscape(1024,1366),true);assert.equal(needsLandscape(1024,1024),true);assert.equal(needsLandscape(1366,1024),false);});
test('front drag adjusts speed smoothly and lifting retains the chosen pace',()=>{const g=fresh(),i=new DualThumbInput(g);i.down(1,100,300,844);i.move(1,175,300,100);const steer=g.steer;assert.equal(steer,.5);const v=g.vx;g.update(1/120);assert.ok(g.vx>v&&g.vx<PHYSICS.fast);i.up(1);assert.equal(g.steer,steer);i.down(2,120,300,844);assert.equal(g.steer,steer);i.up(2,true);i.clear();assert.equal(g.steer,0);});
test('load and release velocity distinguish weak from strong ollies',()=>{const weak=fresh(),strong=fresh();for(const [g,t,dy] of [[weak,.07,0],[strong,.34,-60]]){const i=new DualThumbInput(g);i.down(1,700,300,844,0);step(g,t);i.move(1,700,300+dy,t*1000);i.up(1,false,t*1000+1);}assert.ok(strong.vy>weak.vy+180);});
test('timed front movement levels a rear-only nose-up ollie',()=>{const rear=fresh(),front=fresh();for(const g of [rear,front]){g.rearDown();step(g,.34);g.rearUp();step(g,.16);}front.setFront(true,0,-.6);step(front,.12);front.releaseFront();step(front,.18);step(rear,.30);assert.ok(Math.abs(front.angle)<Math.abs(rear.angle));});
test('four complete course loops remain recoverable and all ledges are passable',()=>{const g=fresh();for(let i=0;i<12000;i++){const next=obstaclesBetween(g.x,g.x+210).find(o=>(o.type==='box'||o.type==='gap'||o.type==='rail')&&o.x>g.x);if(next)demoPop(g);assistDemo(g);g.update(1/120);assert.ok(Number.isFinite(g.x)&&Number.isFinite(g.y));assert.ok(g.y>=0);g.drainEvents();}assert.ok(g.x>22400);assert.equal(g.bails,0);assert.ok(g.ollies>10);assert.ok(g.fiftyFifties>=4);assert.ok(g.combo>=g.ollies);});
test('repeated cancel, finger order, duplicate pop and resets never strand input',()=>{const g=fresh(),input=new DualThumbInput(g);for(let n=0;n<100;n++){input.down(1,100,300,844);input.down(2,700,300,844);input.move(1,800,320,50);assert.equal(input.roles.front,1);assert.equal(input.roles.rear,2);step(g,.1);if(n%2){input.up(1,false,120);input.up(2,true,130);}else{input.up(2,false,120);input.up(1,true,130);}g.pause();input.clear();g.reset();g.start();assert.equal(input.pointers.size,0);assert.equal(g.rear,false);assert.equal(g.front,false);assert.equal(g.catch,false);g.drainEvents();}});
